name: Pull Request Stats

on:
  pull_request:
    types: [opened, reopened, review_requested]
    
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Stats
        uses: flowwer-dev/pull-request-stats@v2.8.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          period: 180
