name: Pull Request Stats

on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.AJSHAJIB_PERSONAL_TOKEN }}
          period: 180
