name: Pull Request Stats

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize ]
    
jobs:
  stats:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          period: 180
